import { MissionLocation } from './types';

// ============================================================
// Seed data: 60 mission destinations
// Each represents a region where the gospel light is needed.
// Educational content is factual and inspiring, written from
// an Adventist Christian missionary perspective.
// ============================================================

export const MISSION_LOCATIONS: MissionLocation[] = [
  {
    id: 'loc-01',
    name: 'The Silk Road Corridor',
    region: 'Central Asia',
    flavorText: 'Ancient trade routes where caravans once carried spices and stories, now silent beneath the weight of forgotten faith.',
    difficulty: 'Deep Darkness',
    image: 'loc-01.jpg',
    image2: 'loc-01-b.jpg',
    beliefSystem: 'Islam (Sunni) / Folk traditions',
    whyHardToReach: 'Government restrictions on religious expression make open evangelism dangerous. Many communities speak minority languages with no Bible translation. Decades of Soviet-era atheism followed by a resurgence of Islam have created deep suspicion of outside religious influence.',
    history: 'The Silk Road once carried Nestorian Christianity deep into Asia, and ancient church ruins still dot the landscape. After centuries of Islamic rule and 70 years of Soviet suppression, the region emerged in the 1990s with almost no indigenous Christian witness. Seventh-day Adventist work began here in the early 1900s but was severely disrupted by persecution.',
    population: '~60 million unreached',
    callToAction: 'The same roads that once carried the gospel east are waiting to hear it again — every nation, kindred, tongue, and people.',
    lat: 41,
    lng: 64,
  },
  {
    id: 'loc-02',
    name: 'The Ganges Delta',
    region: 'South Asia',
    flavorText: 'A vast river delta teeming with life, where spiritual hunger runs as deep as the waterways.',
    difficulty: 'Darkness',
    image: 'loc-02.jpg',
    image2: 'loc-02-b.jpg',
    beliefSystem: 'Hinduism / Islam',
    whyHardToReach: 'Caste-based social structures create powerful barriers to conversion, as accepting Christianity can mean losing family and livelihood. Frequent flooding and extreme poverty make sustained ministry difficult. Anti-conversion laws in several states add legal pressure to social stigma.',
    history: 'William Carey brought the gospel to Bengal in the late 1700s, and the region became a hub for Bible translation. Yet despite over two centuries of Christian presence, vast populations along the delta remain unreached. Adventist mission work in the region has focused on health and education but reaches only a fraction of the population.',
    population: '~250 million unreached',
    callToAction: 'In the land where modern missions began, millions still wait to hear the everlasting gospel and the hope of Christ\'s soon return.',
    lat: 23,
    lng: 80,
  },
  {
    id: 'loc-03',
    name: 'The Sahel Frontier',
    region: 'West Africa',
    flavorText: 'A dry borderland between desert and savanna, where resilience defines every soul who endures.',
    difficulty: 'Unreached',
    image: 'loc-03.jpg',
    image2: 'loc-03-b.jpg',
    beliefSystem: 'Islam (Sunni / Sufi) / Animism',
    whyHardToReach: 'Armed conflict and extremist groups have made large areas unsafe for missionaries. Nomadic lifestyles make it difficult to establish permanent churches or schools. Extreme heat, drought, and food insecurity mean survival often takes priority over everything else.',
    history: 'Islam spread across the Sahel through trade routes beginning in the 8th century, blending with local animist traditions. Christianity arrived later through European colonialism and has grown mostly in the southern regions. The Adventist Church has established schools and clinics, but the northern Sahel remains one of the least-reached regions on Earth.',
    population: '~100 million unreached',
    callToAction: 'Where the desert meets the savanna, God is calling workers to bring living water to those who thirst for truth.',
    lat: 10,
    lng: -5,
  },
  {
    id: 'loc-04',
    name: 'The Jade Mountains',
    region: 'East Asia',
    flavorText: 'Mist-covered peaks hiding villages where the light has only barely begun to dawn.',
    difficulty: 'Deep Darkness',
    image: 'loc-04.jpg',
    image2: 'loc-04-b.jpg',
    beliefSystem: 'Buddhism (Mahayana) / Folk religion / State atheism',
    whyHardToReach: 'Government surveillance and restrictions on unregistered religious activity make evangelism risky. Remote mountain villages are accessible only on foot and lack basic infrastructure. Cultural identity is deeply intertwined with Buddhist and folk traditions, making the gospel seem foreign.',
    history: 'Nestorian missionaries reached China as early as 635 AD, and Jesuit missions followed centuries later. Protestant missions in the 19th century saw significant growth, but the mid-20th century brought severe persecution and the closure of all foreign missions. Underground house churches have grown remarkably despite ongoing pressure.',
    population: '~400 million unreached',
    callToAction: 'Behind the mountains and beyond the restrictions, hearts are being prepared — the Three Angels\' Messages must reach every village.',
    lat: 35,
    lng: 110,
  },
  {
    id: 'loc-05',
    name: 'The Spice Islands',
    region: 'Southeast Asia',
    flavorText: 'Tropical archipelagos rich in beauty and diversity, yet spiritually adrift on the tides.',
    difficulty: 'Twilight',
    image: 'loc-05.jpg',
    image2: 'loc-05-b.jpg',
    beliefSystem: 'Islam (Sunni) / Christianity / Animism',
    whyHardToReach: 'Thousands of islands make logistics a constant challenge, with many communities reachable only by boat. Rising religious nationalism creates social pressure against conversion. The sheer diversity of languages and cultures requires highly localized approaches to ministry.',
    history: 'Portuguese missionaries brought Christianity in the 16th century, and Islam had arrived even earlier through Arab traders. Today the region is a mosaic of faith, with some islands predominantly Christian and others firmly Muslim. Adventist work has been fruitful on certain islands, with strong institutions in health and education.',
    population: '~85 million unreached',
    callToAction: 'Across thousands of islands, the message of hope must travel by boat, by foot, and by faith to every shore.',
    lat: 5,
    lng: 108,
  },
  {
    id: 'loc-06',
    name: 'The Arabian Peninsula',
    region: 'Middle East',
    flavorText: 'A land of ancient prophets and modern wealth, where the deepest thirst is not for water.',
    difficulty: 'Forgotten',
    image: 'loc-06.jpg',
    image2: 'loc-06-b.jpg',
    beliefSystem: 'Islam (Sunni / Wahhabi / Ibadi)',
    whyHardToReach: 'Conversion from Islam is illegal in most countries on the peninsula and can carry the death penalty. Public Christian worship is prohibited or severely restricted. Migrant workers from Christian backgrounds face exploitation, while wealthy nationals rarely encounter the gospel.',
    history: 'Christianity existed in Arabia before Islam, with churches established along the Persian Gulf coast. The rise of Islam in the 7th century eventually eliminated nearly all Christian presence. Today, millions of Christian migrant workers live on the peninsula, creating an unexpected mission field, but reaching Arab nationals remains one of the greatest challenges in world missions.',
    population: '~55 million unreached',
    callToAction: 'In the land where Abraham journeyed and prophets walked, God still has people who will respond to His final call.',
    lat: 30,
    lng: 42,
  },
  {
    id: 'loc-07',
    name: 'The Steppe Lands',
    region: 'Central Asia',
    flavorText: 'Endless grasslands where nomadic traditions endure, untouched by outside voices for generations.',
    difficulty: 'Unreached',
    image: 'loc-07.jpg',
    image2: 'loc-07-b.jpg',
    beliefSystem: 'Islam (Sunni) / Shamanism / Tengrism',
    whyHardToReach: 'Nomadic communities move seasonally, making it hard to maintain ongoing relationships and discipleship. Cultural identity is deeply tied to a blend of Islamic and shamanistic practices. Government registration requirements and surveillance of religious groups limit ministry options.',
    history: 'The steppe peoples have a rich spiritual heritage blending sky-worship (Tengrism) with Islam adopted centuries ago through trade and conquest. Soviet-era suppression of religion left a spiritual vacuum that has been filled unevenly. Small Adventist congregations exist in urban areas but have had minimal impact on the vast rural steppe.',
    population: '~20 million unreached',
    callToAction: 'Under the vast sky of the steppe, the Creator is calling His children home — the gospel must ride to every yurt and village.',
    lat: 39,
    lng: 68,
  },
  {
    id: 'loc-08',
    name: 'The Nile Headwaters',
    region: 'East Africa',
    flavorText: 'Where the great river begins, communities gather in the shadow of old beliefs and new struggles.',
    difficulty: 'Twilight',
    image: 'loc-08.jpg',
    image2: 'loc-08-b.jpg',
    beliefSystem: 'Christianity (various) / Islam / Traditional religions',
    whyHardToReach: 'Ethnic conflict and political instability displace communities and disrupt ministry efforts. Syncretic blending of Christianity with traditional practices obscures the biblical message. Poverty and limited access to education make sustained discipleship challenging.',
    history: 'Ethiopia and the Great Lakes region have some of the oldest Christian traditions in the world, dating to the Ethiopian eunuch in Acts. Yet many ethnic groups in the highlands and lake regions have had minimal exposure to biblical Christianity. Adventist work in East Africa has seen strong growth, but significant unreached pockets remain.',
    population: '~30 million unreached',
    callToAction: 'At the source of the Nile, the living water of the gospel can flow to communities that have waited for generations.',
    lat: -2,
    lng: 37,
  },
  {
    id: 'loc-09',
    name: 'The Himalayan Passes',
    region: 'South Asia',
    flavorText: 'Remote highland corridors where thin air and thinner roads keep the world at bay.',
    difficulty: 'Forgotten',
    image: 'loc-09.jpg',
    image2: 'loc-09-b.jpg',
    beliefSystem: 'Buddhism (Tibetan / Vajrayana) / Hinduism / Bon',
    whyHardToReach: 'Extreme altitude and harsh winters isolate communities for months at a time. Buddhist monastic culture is deeply embedded in every aspect of daily life, from governance to agriculture. Political sensitivities between neighboring nations make cross-border ministry nearly impossible.',
    history: 'Tibetan Buddhism has shaped Himalayan culture for over a thousand years, creating a rich but insular spiritual world. Early Moravian missionaries made limited inroads in Ladakh in the 1800s, but most Himalayan communities have never had sustained Christian witness. The region remains one of the least evangelized on Earth.',
    population: '~15 million unreached',
    callToAction: 'At the roof of the world, where prayer flags flutter in the wind, the message of a soon-coming Savior has yet to be heard.',
    lat: 27,
    lng: 84,
  },
  {
    id: 'loc-10',
    name: 'The Mekong Basin',
    region: 'Southeast Asia',
    flavorText: 'Lush river valleys sustaining millions, where ancient temples cast long shadows over the present.',
    difficulty: 'Darkness',
    image: 'loc-10.jpg',
    image2: 'loc-10-b.jpg',
    beliefSystem: 'Buddhism (Theravada) / Animism',
    whyHardToReach: 'Theravada Buddhism is deeply woven into national identity, and leaving it is seen as a betrayal of culture and family. Government restrictions on proselytism exist in several Mekong nations. Rural communities along the river are often accessible only by boat and lack basic infrastructure.',
    history: 'Theravada Buddhism arrived in the Mekong region over a thousand years ago and became the state religion of multiple kingdoms. Christian missions began in earnest in the 19th century but made limited headway among Buddhist-majority populations. Adventist work in the region has focused on urban centers, leaving vast rural stretches along the river largely untouched.',
    population: '~70 million unreached',
    callToAction: 'Along the Mekong\'s banks, where golden temples glow at sunset, millions are waiting to discover the true Light of the world.',
    lat: 15,
    lng: 103,
  },
  {
    id: 'loc-11',
    name: 'The Atlas Foothills',
    region: 'North Africa',
    flavorText: 'Rocky highlands where Berber villages cling to the mountainside, proud and self-sufficient.',
    difficulty: 'Deep Darkness',
    image: 'loc-11.jpg',
    image2: 'loc-11-b.jpg',
    beliefSystem: 'Islam (Sunni / Maliki) / Berber traditions',
    whyHardToReach: 'Anti-conversion laws and social ostracism make faith changes extremely costly. Berber communities are tight-knit and suspicious of outside religious influence. Bible resources in Berber languages remain limited, though translation work is ongoing.',
    history: 'North Africa was once a stronghold of early Christianity — home to Augustine, Tertullian, and Cyprian. The Arab conquest of the 7th century gradually replaced Christianity with Islam. Today, a quiet movement of Berber believers is growing, but the vast majority have never heard a clear presentation of the gospel.',
    population: '~25 million unreached',
    callToAction: 'In the land of Augustine and the early church fathers, the seeds of faith are stirring again — the harvest is not forgotten.',
    lat: 28,
    lng: 8,
  },
  {
    id: 'loc-12',
    name: 'The Persian Plateau',
    region: 'Middle East',
    flavorText: 'An ancient crossroads of empires, now quietly guarding traditions older than memory.',
    difficulty: 'Forgotten',
    image: 'loc-12.jpg',
    image2: 'loc-12-b.jpg',
    beliefSystem: 'Islam (Shia) / Zoroastrianism (remnant)',
    whyHardToReach: 'Conversion from Islam is considered apostasy and can result in imprisonment or death. Internet and media are heavily censored, limiting digital evangelism. Despite these barriers, an underground church movement is one of the fastest-growing in the world.',
    history: 'Persia was one of the earliest regions to receive the gospel, with tradition placing the apostle Thomas passing through on his way east. The Persian church thrived for centuries before the Islamic conquest. In recent decades, disillusionment with the religious establishment has driven unprecedented openness to Christianity, creating a remarkable underground movement.',
    population: '~80 million unreached',
    callToAction: 'Behind closed doors across the Persian Plateau, the Holy Spirit is moving with power — pray that the light cannot be hidden.',
    lat: 32,
    lng: 53,
  },
  {
    id: 'loc-13',
    name: 'The Bay of Bengal Coast',
    region: 'South Asia',
    flavorText: 'Fishing villages stretched along a warm coast, where the horizon holds both promise and peril.',
    difficulty: 'Twilight',
    image: 'loc-13.jpg',
    image2: 'loc-13-b.jpg',
    beliefSystem: 'Buddhism (Theravada) / Islam / Hinduism',
    whyHardToReach: 'Cyclones and flooding regularly devastate coastal communities, making long-term ministry difficult. Ethnic and religious tensions between majority and minority groups create volatile environments. Many fishing communities are economically marginalized and geographically isolated.',
    history: 'The Bay of Bengal coast has been a crossroads of trade and religion for millennia, with influences from India, Arabia, and Southeast Asia. Adoniram Judson, one of the first American missionaries, labored here for decades in the early 1800s. Adventist work exists in the region but faces significant challenges reaching the diverse coastal communities.',
    population: '~45 million unreached',
    callToAction: 'Along the Bay of Bengal, where fishermen cast their nets each morning, the call goes out: come and fish for people.',
    lat: 21,
    lng: 86,
  },
  {
    id: 'loc-14',
    name: 'The Gobi Expanse',
    region: 'East Asia',
    flavorText: 'A vast desert where silence speaks louder than any sermon, and survival is its own faith.',
    difficulty: 'Unreached',
    image: 'loc-14.jpg',
    image2: 'loc-14-b.jpg',
    beliefSystem: 'Buddhism (Tibetan) / Shamanism / State atheism',
    whyHardToReach: 'Extreme climate with temperatures ranging from -40C to 45C makes permanent settlement difficult. Nomadic herders move constantly, and population density is among the lowest on Earth. Decades of state atheism have left deep spiritual emptiness combined with distrust of organized religion.',
    history: 'The Mongol Empire under Genghis Khan was surprisingly tolerant of religions, and Nestorian Christians held significant influence in the medieval court. The later adoption of Tibetan Buddhism reshaped Mongolian identity. After decades of Soviet-influenced atheism, a spiritual renaissance began in the 1990s, and small Christian communities have emerged in urban areas.',
    population: '~3 million unreached',
    callToAction: 'In the vast silence of the Gobi, God knows every nomad by name — the everlasting gospel is for every soul under this endless sky.',
    lat: 43,
    lng: 105,
  },
  {
    id: 'loc-15',
    name: 'The Indus Valley',
    region: 'South Asia',
    flavorText: 'Cradle of one of humanity\'s oldest civilizations, where layers of belief run deeper than the soil.',
    difficulty: 'Darkness',
    image: 'loc-15.jpg',
    image2: 'loc-15-b.jpg',
    beliefSystem: 'Islam (Sunni) / Hinduism (minority)',
    whyHardToReach: 'Blasphemy laws are used to target religious minorities, creating a climate of fear. Tribal and feudal social structures in rural areas make individual faith decisions nearly impossible. Extremist violence against Christians and other minorities is a persistent threat.',
    history: 'The Indus Valley was home to one of the world\'s earliest civilizations and has been shaped by wave after wave of cultural and religious change. The apostle Thomas is traditionally believed to have preached in this region. Today, a small but resilient Christian community exists, facing significant persecution while bearing faithful witness.',
    population: '~190 million unreached',
    callToAction: 'In one of civilization\'s oldest cradles, the newest hope — the soon return of Jesus — must still be proclaimed.',
    lat: 25,
    lng: 68,
  },
  {
    id: 'loc-16',
    name: 'The Horn of Africa',
    region: 'East Africa',
    flavorText: 'A strategic point where continents nearly touch, and conflict and hope walk side by side.',
    difficulty: 'Deep Darkness',
    image: 'loc-16.jpg',
    image2: 'loc-16-b.jpg',
    beliefSystem: 'Islam (Sunni) / Ethiopian Orthodoxy / Traditional religions',
    whyHardToReach: 'Ongoing civil wars and famine create humanitarian crises that overshadow spiritual needs. Clan-based society means conversion affects entire extended families and can lead to violent reprisals. Al-Shabaab and other extremist groups actively target Christian workers.',
    history: 'The Horn of Africa includes one of the oldest Christian nations (Ethiopia, since the 4th century) alongside deeply Muslim regions. The region has been shaped by colonialism, Cold War proxy conflicts, and devastating famines. Adventist work in Ethiopia has been remarkably fruitful, but neighboring regions like Somalia remain among the most dangerous places on Earth for Christians.',
    population: '~65 million unreached',
    callToAction: 'Where Africa meets the sea, where suffering meets courage, the message of a God who heals and restores is urgently needed.',
    lat: 8,
    lng: 45,
  },
  {
    id: 'loc-17',
    name: 'The Yangtze Lowlands',
    region: 'East Asia',
    flavorText: 'A crowded trade city full of movement, distraction, and spiritual hunger.',
    difficulty: 'Twilight',
    image: 'loc-17.jpg',
    image2: 'loc-17-b.jpg',
    beliefSystem: 'Folk religion / Buddhism / State atheism / Christianity (growing)',
    whyHardToReach: 'Rapid urbanization and materialism compete powerfully with spiritual concerns. Government oversight of registered churches limits theological freedom. The sheer scale of the population means that even a large church represents a tiny fraction of the whole.',
    history: 'Hudson Taylor and other pioneering missionaries established significant Christian work along the Yangtze in the 19th century. After 1949, the church went underground and emerged decades later remarkably stronger. Today, Christianity is one of the fastest-growing movements in the region, yet hundreds of millions have still not heard a clear gospel presentation.',
    population: '~300 million unreached',
    callToAction: 'In the bustling heart of the world\'s most populous region, the still small voice of the Spirit is calling millions to find rest in Christ.',
    lat: 31,
    lng: 118,
  },
  {
    id: 'loc-18',
    name: 'The Caucasus Valleys',
    region: 'Eurasia',
    flavorText: 'Mountain-locked valleys where ancient churches stand empty and new voices are seldom heard.',
    difficulty: 'Darkness',
    image: 'loc-18.jpg',
    image2: 'loc-18-b.jpg',
    beliefSystem: 'Islam (Sunni / Sufi) / Eastern Orthodoxy / Ancient churches',
    whyHardToReach: 'Ethnic conflicts and frozen wars create dangerous and unstable environments. National identity is deeply tied to either Orthodox Christianity or Islam, leaving little space for new movements. Mountainous terrain isolates communities, and many minority languages lack Scripture translations.',
    history: 'The Caucasus was one of the first regions to adopt Christianity, with Armenia and Georgia converting in the early 4th century. However, neighboring valleys adopted Islam centuries later. The Soviet era suppressed all religion, and the post-Soviet period has seen both revival and radicalization. Adventist congregations exist but are very small.',
    population: '~15 million unreached',
    callToAction: 'In valleys where the gospel first took root nearly two thousand years ago, fresh seeds of truth are ready to be planted.',
    lat: 55,
    lng: 50,
  },
  {
    id: 'loc-19',
    name: 'The Sundarbans',
    region: 'South Asia',
    flavorText: 'Mangrove forests where the land itself seems uncertain, and communities live between worlds.',
    difficulty: 'Unreached',
    image: 'loc-19.jpg',
    image2: 'loc-19-b.jpg',
    beliefSystem: 'Islam / Hinduism / Folk religions',
    whyHardToReach: 'The world\'s largest mangrove forest is accessible only by boat, and communities are spread across thousands of small islands. Rising sea levels and devastating cyclones regularly displace entire villages. Extreme poverty and lack of education create additional barriers to sustained ministry.',
    history: 'The Sundarbans have been home to forest-dwelling communities for centuries, living in harmony with the tides and the Bengal tiger. Historically overlooked by both colonial and mission efforts, these communities developed unique syncretic spiritual practices. Christian presence in the region remains minimal despite the tremendous physical and spiritual needs.',
    population: '~4 million unreached',
    callToAction: 'In the tangled waterways where land and sea blur together, the solid foundation of God\'s love is the anchor these communities need.',
    lat: 22,
    lng: 89,
  },
  {
    id: 'loc-20',
    name: 'The Rift Valley',
    region: 'East Africa',
    flavorText: 'A geological scar across the continent, home to peoples whose stories rarely travel beyond the ridge.',
    difficulty: 'Twilight',
    image: 'loc-20.jpg',
    image2: 'loc-20-b.jpg',
    beliefSystem: 'Christianity (various) / Islam / Traditional religions',
    whyHardToReach: 'Pastoral communities move with their herds and resist settlement-based ministry models. Tribal identity is stronger than national or religious identity, requiring deeply contextualized approaches. Limited infrastructure means many communities are days from the nearest road.',
    history: 'The Rift Valley is humanity\'s birthplace, and its peoples have some of the most ancient cultural traditions on Earth. Christianity has grown significantly in urban centers and settled agricultural areas, but nomadic pastoralists like the Maasai, Turkana, and others remain largely unreached. Adventist mission stations have been established along the valley with growing success.',
    population: '~20 million unreached',
    callToAction: 'In the valley where humanity began, God\'s final message of redemption must reach every people group before the story ends.',
    lat: -3,
    lng: 36,
  },
  {
    id: 'loc-21',
    name: 'The Thar Desert',
    region: 'South Asia',
    flavorText: 'Golden dunes stretching beyond sight, where oasis communities guard their ways with quiet determination.',
    difficulty: 'Forgotten',
    image: 'loc-21.jpg',
    image2: 'loc-21-b.jpg',
    beliefSystem: 'Hinduism / Islam / Jainism',
    whyHardToReach: 'Extreme heat and water scarcity make the region inhospitable for outside workers. The rigid caste system means lower-caste converts face severe social consequences. Anti-conversion sentiment is strong, and foreign missionaries face visa restrictions and surveillance.',
    history: 'The Thar Desert has been inhabited for millennia, with communities developing sophisticated water harvesting systems to survive. Rajput warrior culture and deep Hindu devotion have defined the region\'s identity. Christian missions have had minimal presence here, and the Adventist Church has only scattered members in the surrounding cities.',
    population: '~30 million unreached',
    callToAction: 'Across the golden sands of the Thar, people of deep devotion are waiting to discover the God who knows them and calls them by name.',
    lat: 26,
    lng: 72,
  },
  {
    id: 'loc-22',
    name: 'The Fergana Valley',
    region: 'Central Asia',
    flavorText: 'A fertile pocket surrounded by mountains, where old Soviet structures crumble beside ancient mosques.',
    difficulty: 'Deep Darkness',
    image: 'loc-22.jpg',
    image2: 'loc-22-b.jpg',
    beliefSystem: 'Islam (Sunni / Hanafi) / Sufism',
    whyHardToReach: 'The valley is divided among three nations with tense borders, complicating cross-border ministry. Government crackdowns on unregistered religious groups are frequent and severe. Islamic identity is deeply connected to ethnic identity, making conversion culturally unthinkable for many.',
    history: 'The Fergana Valley was a major center of Islamic learning and Sufi mysticism for centuries. Soviet rule suppressed religion but couldn\'t eliminate it; underground Islamic networks survived and emerged stronger after independence. Christian witness has been sporadic and faces intense opposition from both government and community.',
    population: '~14 million unreached',
    callToAction: 'In the fertile heart of Central Asia, where ancient faith runs deep, the seeds of present truth are longing to take root.',
    lat: 40,
    lng: 71,
  },
  {
    id: 'loc-23',
    name: 'The Malay Straits',
    region: 'Southeast Asia',
    flavorText: 'Busy shipping lanes where cultures collide, and faith is as fluid as the water beneath the hulls.',
    difficulty: 'Darkness',
    image: 'loc-23.jpg',
    image2: 'loc-23-b.jpg',
    beliefSystem: 'Islam (Sunni / Shafi\'i) / Buddhism / Hinduism',
    whyHardToReach: 'Constitutional definitions tying ethnic identity to Islam make conversion legally and socially nearly impossible. Apostasy laws carry severe consequences including loss of custody and inheritance. While religious freedom exists on paper, social and legal enforcement heavily favors Islam.',
    history: 'The Malay world was Hindu-Buddhist for centuries before Arab and Indian traders brought Islam in the 13th century. Portuguese and Dutch colonizers brought Christianity, which took hold among Chinese and Indian minorities but not among ethnic Malays. Adventist work in the region has focused on non-Malay communities, with reaching Muslim Malays remaining one of the great unfinished tasks.',
    population: '~25 million unreached',
    callToAction: 'At the crossroads of the world\'s busiest shipping lanes, the most precious cargo — the gospel — must still be delivered.',
    lat: 4,
    lng: 102,
  },
  {
    id: 'loc-24',
    name: 'The Tigris Marshlands',
    region: 'Middle East',
    flavorText: 'Reed-house villages floating on ancient waters, isolated from the world by choice and circumstance.',
    difficulty: 'Unreached',
    image: 'loc-24.jpg',
    image2: 'loc-24-b.jpg',
    beliefSystem: 'Islam (Shia) / Mandaeism',
    whyHardToReach: 'Decades of war and deliberate draining of the marshlands destroyed communities and displaced populations. The remaining Marsh Arabs live in extreme poverty with almost no access to outside resources. Security concerns and distrust of outsiders make establishing relationships very difficult.',
    history: 'The Tigris-Euphrates marshlands are the probable location of the biblical Garden of Eden and the cradle of civilization. The Marsh Arabs maintained a unique way of life for five thousand years until Saddam Hussein drained the marshes in the 1990s as punishment for rebellion. Partial restoration has begun, but the communities remain fragmented and traumatized.',
    population: '~500,000 unreached',
    callToAction: 'In the land where Eden once bloomed, restoration is possible — God\'s promise of a new creation offers hope to the brokenhearted.',
    lat: 31,
    lng: 47,
  },
  {
    id: 'loc-25',
    name: 'The Congo Basin',
    region: 'Central Africa',
    flavorText: 'Dense rainforest hiding communities who measure time by the river, not the clock.',
    difficulty: 'Deep Darkness',
    image: 'loc-25.jpg',
    image2: 'loc-25-b.jpg',
    beliefSystem: 'Christianity (syncretic) / Animism / Islam',
    whyHardToReach: 'Armed conflict, militia activity, and lawlessness make large areas extremely dangerous. The dense rainforest and lack of roads mean some communities are weeks of travel from the nearest town. Syncretic Christianity blends the gospel with ancestral spirit worship, obscuring the biblical message.',
    history: 'European missionaries entered the Congo Basin in the late 19th century alongside colonizers, creating a complicated legacy. Christianity spread rapidly but often mixed with traditional practices. The Adventist Church has one of its largest African memberships in this region, yet deep in the forest, thousands of communities remain unreached or follow a syncretic version of the faith.',
    population: '~35 million unreached',
    callToAction: 'Deep in the world\'s second-largest rainforest, the Light that shines in darkness is calling every hidden community into His marvelous light.',
    lat: 0,
    lng: 22,
  },
  {
    id: 'loc-26',
    name: 'The Taklamakan Edge',
    region: 'East Asia',
    flavorText: 'Oasis towns ringing a desert so forbidding that its name means "go in and you won\'t come out."',
    difficulty: 'Forgotten',
    image: 'loc-26.jpg',
    image2: 'loc-26-b.jpg',
    beliefSystem: 'Islam (Sunni) / Folk traditions',
    whyHardToReach: 'Intense government surveillance and restrictions on religious practice, especially for ethnic minorities, create an atmosphere of fear. Cultural genocide concerns have drawn international attention, but access for outside observers and missionaries is essentially zero. The local language has limited Scripture resources.',
    history: 'The oasis cities of the Taklamakan were vital Silk Road stops where Buddhism, Manichaeism, and eventually Islam flourished. Ancient Christian manuscripts have been found in desert ruins, proving the gospel reached here over a thousand years ago. Today, the Uyghur people face severe repression, and the few known believers worship in extreme secrecy.',
    population: '~12 million unreached',
    callToAction: 'Where ancient manuscripts whisper of a gospel once known and then forgotten, God has not forgotten His people — and neither must we.',
    lat: 40,
    lng: 80,
  },
  {
    id: 'loc-27',
    name: 'The Balkan Highlands',
    region: 'Europe',
    flavorText: 'Mountain communities where old wounds and older faiths intertwine in ways outsiders rarely understand.',
    difficulty: 'Twilight',
    image: 'loc-27.jpg',
    image2: 'loc-27-b.jpg',
    beliefSystem: 'Islam (Sunni) / Eastern Orthodoxy / Catholicism',
    whyHardToReach: 'Religious identity is deeply intertwined with ethnic identity, making conversion feel like ethnic betrayal. Memories of religious violence from the 1990s wars have hardened boundaries between communities. Secularism and materialism among younger generations create a different kind of resistance.',
    history: 'The Balkans have been a fault line between Christianity and Islam for over five centuries since the Ottoman conquest. The devastating wars of the 1990s were partly fought along religious and ethnic lines, leaving deep scars. Adventist work in the Balkans dates to the late 1800s and continues through small but faithful communities.',
    population: '~8 million unreached',
    callToAction: 'In Europe\'s most religiously divided region, the unifying message of God\'s love can heal wounds that politics never will.',
    lat: 44,
    lng: 20,
  },
  {
    id: 'loc-28',
    name: 'The Irrawaddy Delta',
    region: 'Southeast Asia',
    flavorText: 'Fertile lowlands rebuilt after storms, where resilience is practiced daily but hope is in short supply.',
    difficulty: 'Darkness',
    image: 'loc-28.jpg',
    image2: 'loc-28-b.jpg',
    beliefSystem: 'Buddhism (Theravada) / Animism / Christianity (minority)',
    whyHardToReach: 'Military governance and civil conflict have created one of the world\'s largest displacement crises. Buddhist nationalism views Christianity as a colonial remnant and a threat to national identity. Cyclone Nargis devastated the delta in 2008, and communities are still rebuilding.',
    history: 'Adoniram Judson spent decades translating the Bible into Burmese in the early 1800s, and Christianity took root especially among ethnic minorities like the Karen and Chin. The majority Bamar people remain overwhelmingly Buddhist. Adventist work began in the early 1900s and has grown among ethnic minorities, but the delta\'s Buddhist population remains largely unreached.',
    population: '~40 million unreached',
    callToAction: 'In a land shaped by storms both natural and political, the peace that passes understanding is the message the delta desperately needs.',
    lat: 17,
    lng: 96,
  },
  {
    id: 'loc-29',
    name: 'The Pamir Plateau',
    region: 'Central Asia',
    flavorText: 'The roof of the world, where thin air and vast distances make every journey an act of faith.',
    difficulty: 'Unreached',
    image: 'loc-29.jpg',
    image2: 'loc-29-b.jpg',
    beliefSystem: 'Islam (Ismaili Shia) / Folk traditions',
    whyHardToReach: 'Extreme altitude and isolation — some communities are accessible only a few months per year. The small population is spread across vast distances with minimal infrastructure. Ismaili Islam creates a unique cultural context that differs significantly from the Sunni majority around it.',
    history: 'The Pamir region has been a crossroads of empires for millennia, situated along the ancient Silk Road at the junction of modern-day Tajikistan, China, Afghanistan, and Pakistan. The Ismaili community follows the Aga Khan\'s leadership and has developed a distinct cultural identity. Christian presence is virtually nonexistent, with no known established church in the region.',
    population: '~250,000 unreached',
    callToAction: 'At the roof of the world, where the sky feels close enough to touch, the God of heaven is reaching down to gather His scattered children.',
    lat: 37,
    lng: 73,
  },
  {
    id: 'loc-30',
    name: 'The Deccan Plateau',
    region: 'South Asia',
    flavorText: 'A broad tableland dotted with ancient temples and modern cities, where old and new devotions compete.',
    difficulty: 'Twilight',
    image: 'loc-30.jpg',
    image2: 'loc-30-b.jpg',
    beliefSystem: 'Hinduism / Islam / Buddhism (Dalit converts)',
    whyHardToReach: 'Hindu nationalist movements have intensified pressure on Christian minorities through anti-conversion laws and social intimidation. Rural communities are deeply embedded in caste-based Hindu practice with little exposure to alternatives. Rapid urbanization creates both opportunity and distraction as millions chase economic advancement.',
    history: 'The Deccan has been shaped by Hindu kingdoms, Muslim sultanates, and British colonialism in succession. Dr. B.R. Ambedkar\'s mass conversion movement brought millions of Dalits to Buddhism in the 1950s as a protest against caste discrimination. Adventist work on the Deccan Plateau includes schools and hospitals that have created goodwill, but the broader population remains largely Hindu.',
    population: '~200 million unreached',
    callToAction: 'Across the vast Deccan Plateau, where ancient and modern India meet, the timeless message of freedom in Christ offers hope to every caste and community.',
    lat: 18,
    lng: 76,
  },
  {
    id: 'loc-31',
    name: 'The Pashtun Highlands',
    region: 'South Asia',
    flavorText: 'Rugged mountain passes where the code of honor runs deeper than any road, and strangers are met with both hospitality and suspicion.',
    difficulty: 'Forgotten',
    image: 'loc-31.jpg',
    image2: 'loc-31-b.jpg',
    beliefSystem: 'Islam (Sunni / Deobandi) / Pashtunwali code',
    whyHardToReach: 'The Pashtun code of Pashtunwali governs all aspects of life, and leaving Islam is considered a betrayal of tribal identity punishable by death. Decades of war in Afghanistan and Pakistan\'s tribal areas have made the region one of the most dangerous on Earth. Women are almost entirely inaccessible to outside influence, and literacy rates are among the world\'s lowest.',
    history: 'The Pashtun people, numbering over 50 million, are the largest patriarchal ethnic group in the world without a significant Christian movement. Despite bordering regions where Christianity has existed for centuries, the Pashtun heartland has remained virtually untouched by the gospel. A handful of secret believers exist but face extreme danger if discovered.',
    population: '~50 million unreached',
    callToAction: 'Among the Pashtun, where honor and hospitality define every interaction, the gospel of grace offers a new covenant of belonging.',
    lat: 33,
    lng: 70,
  },
  {
    id: 'loc-32',
    name: 'The Balochistan Expanse',
    region: 'South Asia / Middle East',
    flavorText: 'A sun-scorched wilderness stretching across three nations, where the Baloch people wander with their flocks and their ancient ways.',
    difficulty: 'Forgotten',
    image: 'loc-32.jpg',
    image2: 'loc-32-b.jpg',
    beliefSystem: 'Islam (Sunni / Hanafi) / Zikri sect',
    whyHardToReach: 'The Baloch homeland spans Pakistan, Iran, and Afghanistan, making coordinated outreach nearly impossible. Insurgency and military operations create a volatile security environment. Extreme desert conditions and sparse population density mean communities are separated by vast uninhabited stretches.',
    history: 'The Baloch people have maintained a distinct identity for over a thousand years despite being divided across three modern nations. A unique Zikri sect within Baloch Islam practices rituals distinct from mainstream Sunni worship. There is no known organized Christian witness among the Baloch, and Scripture translation into Balochi dialects remains incomplete.',
    population: '~15 million unreached',
    callToAction: 'Across the windswept expanse of Balochistan, a people divided by borders but united in identity await the message that unites all nations.',
    lat: 28,
    lng: 64,
  },
  {
    id: 'loc-33',
    name: 'The Taklamakan Oasis Cities',
    region: 'East Asia',
    flavorText: 'Behind surveillance cameras and concrete walls, a people cling to their identity in whispered prayers and hidden songs.',
    difficulty: 'Forgotten',
    image: 'loc-33.jpg',
    image2: 'loc-33-b.jpg',
    beliefSystem: 'Islam (Sunni) / Uyghur cultural traditions',
    whyHardToReach: 'The Uyghur people face mass surveillance, detention programs, and systematic cultural suppression that makes any religious activity outside state control extremely dangerous. Foreign access to the region is tightly controlled, and digital communications are monitored. The trauma of recent persecution has created deep distrust of any outside engagement.',
    history: 'The Uyghurs once lived along the Silk Road where Buddhism, Manichaeism, and Nestorian Christianity all flourished before Islam became dominant around the 10th century. Ancient Christian manuscripts in Old Uyghur script prove the gospel was known here over a millennium ago. Today, the estimated 12 million Uyghurs have virtually no access to Christian witness amid severe repression.',
    population: '~12 million unreached',
    callToAction: 'Where ancient Silk Road believers once worshiped freely, a people under immense pressure need the prayers and solidarity of the global church.',
    lat: 39,
    lng: 76,
  },
  {
    id: 'loc-34',
    name: 'The Rakhine Coast',
    region: 'Southeast Asia',
    flavorText: 'Refugee camps stretching to the horizon, where a displaced people carry their faith and their grief across muddy borders.',
    difficulty: 'Deep Darkness',
    image: 'loc-34.jpg',
    image2: 'loc-34-b.jpg',
    beliefSystem: 'Islam (Sunni)',
    whyHardToReach: 'The Rohingya people have been displaced by violence and denied citizenship, creating one of the world\'s largest refugee crises. Camp conditions in Bangladesh and displacement within Myanmar make sustained ministry extremely challenging. Deep trauma from persecution requires sensitive, long-term relational engagement before spiritual conversations are possible.',
    history: 'The Rohingya are a Muslim ethnic group from Myanmar\'s Rakhine State who have faced decades of persecution culminating in mass displacement since 2017. Over a million refugees live in camps in Cox\'s Bazar, Bangladesh. Christian humanitarian organizations serve in the camps, but evangelistic outreach among this traumatized community requires extraordinary patience and compassion.',
    population: '~2 million unreached',
    callToAction: 'Among the Rohingya, a people who have lost nearly everything, the message of a God who sees the forgotten offers hope no camp can contain.',
    lat: 21,
    lng: 92,
  },
  {
    id: 'loc-35',
    name: 'The Somali Coastlands',
    region: 'East Africa',
    flavorText: 'A fractured nation of poets and traders, where the Indian Ocean whispers of connections that war has severed.',
    difficulty: 'Forgotten',
    image: 'loc-35.jpg',
    image2: 'loc-35-b.jpg',
    beliefSystem: 'Islam (Sunni / Shafi\'i) / Sufi orders',
    whyHardToReach: 'Decades of civil war and the presence of Al-Shabaab make Somalia one of the most dangerous countries for Christians. Somali identity is inseparable from Islam — to be Somali is to be Muslim. The few known Somali believers face death threats from family and community, and most flee the country upon conversion.',
    history: 'Islam reached the Somali coast through Arab traders in the 7th century and has been central to Somali identity ever since. Colonial-era missions made almost no inroads among ethnic Somalis. Today, a small but growing number of Somali believers exist in the diaspora, using media and personal networks to share their faith, but the homeland remains one of the hardest places on Earth to follow Christ.',
    population: '~18 million unreached',
    callToAction: 'In a land of poets and survivors, the greatest story ever told is still waiting to be heard in the Somali tongue.',
    lat: 5,
    lng: 46,
  },
  {
    id: 'loc-36',
    name: 'The Kabyle Mountains',
    region: 'North Africa',
    flavorText: 'Terraced villages clinging to steep slopes, where an ancient Berber people quietly rediscover a faith older than the conquest.',
    difficulty: 'Deep Darkness',
    image: 'loc-36.jpg',
    image2: 'loc-36-b.jpg',
    beliefSystem: 'Islam (Sunni / Maliki) / Berber traditions',
    whyHardToReach: 'While a remarkable movement of Kabyle believers has emerged in recent decades, converts still face family rejection and legal restrictions on non-Muslim worship. Church buildings have been ordered closed by authorities, and social pressure remains intense. The movement is fragile and needs sustained prayer and support.',
    history: 'The Kabyle are the largest Berber subgroup in Algeria, and their region was once home to flourishing early Christian communities before the Arab conquest. In recent decades, a surprising spiritual awakening has brought thousands of Kabyle to faith in Christ, making it one of the most significant movements in the Muslim world. Yet the vast majority of Kabyle people remain unreached.',
    population: '~7 million unreached',
    callToAction: 'In the mountains where Augustine\'s North African church once thrived, the Spirit is moving again among the Kabyle — pray for the harvest.',
    lat: 36,
    lng: 4,
  },
  {
    id: 'loc-37',
    name: 'The Bedouin Wilderness',
    region: 'Middle East / North Africa',
    flavorText: 'Desert wanderers whose hospitality is legendary, moving with their herds across borders that mean nothing beneath the stars.',
    difficulty: 'Unreached',
    image: 'loc-37.jpg',
    image2: 'loc-37-b.jpg',
    beliefSystem: 'Islam (Sunni) / Pre-Islamic desert traditions',
    whyHardToReach: 'Bedouin nomadic lifestyle makes sustained engagement extremely difficult as families move seasonally across vast distances. Tribal loyalty structures mean individual conversion disrupts the entire clan. Bedouin communities span multiple countries with different legal frameworks, complicating any coordinated outreach.',
    history: 'The Bedouin are the original Arab people, whose culture predates Islam and whose hospitality traditions echo the biblical patriarchs. Christianity was present among some Arab tribes before Muhammad, and the New Testament mentions Arabia as a place Paul visited. Today, scattered Bedouin believers exist but face intense pressure to conform to tribal Islamic identity.',
    population: '~25 million unreached',
    callToAction: 'Under the same stars that guided Abraham through the wilderness, Bedouin hearts are being prepared to receive the promise given to all nations.',
    lat: 28,
    lng: 35,
  },
  {
    id: 'loc-38',
    name: 'The Kurdish Highlands',
    region: 'Middle East',
    flavorText: 'Mountain strongholds of a stateless nation, where resilience has been forged through centuries of resistance and survival.',
    difficulty: 'Deep Darkness',
    image: 'loc-38.jpg',
    image2: 'loc-38-b.jpg',
    beliefSystem: 'Islam (Sunni / Shafi\'i) / Yezidism / Alevism',
    whyHardToReach: 'The Kurdish people are divided across four nations — Turkey, Iraq, Iran, and Syria — each with different levels of access and restriction. Ongoing military conflicts and political instability create dangerous conditions. While some Kurds are religiously diverse, conversion from Islam carries severe social consequences in most communities.',
    history: 'The Kurds are the world\'s largest stateless nation, with a population of 30-40 million spread across the Middle East. The region includes ancient Assyrian Christian communities that predate Islam. Recent conflicts have displaced millions of Kurds and created humanitarian crises, but also unprecedented openness in some areas, particularly in Iraqi Kurdistan where religious freedom is comparatively greater.',
    population: '~30 million unreached',
    callToAction: 'Among a people who have long fought for a homeland, the kingdom of God offers citizenship that no border can deny.',
    lat: 37,
    lng: 44,
  },
  {
    id: 'loc-39',
    name: 'The Tibetan Plateau',
    region: 'East Asia',
    flavorText: 'Nomadic herders move across the highest inhabited plateau on Earth, where prayer wheels spin in the thin mountain air.',
    difficulty: 'Forgotten',
    image: 'loc-39.jpg',
    image2: 'loc-39-b.jpg',
    beliefSystem: 'Buddhism (Tibetan / Vajrayana) / Bon',
    whyHardToReach: 'Tibetan Buddhist identity is inseparable from cultural and national identity, making conversion feel like cultural erasure. Nomadic communities on the plateau live at altitudes above 4,000 meters and are accessible only during brief summer months. Government restrictions on religious activity and foreign access are severe.',
    history: 'Tibetan Buddhism has shaped every aspect of Tibetan culture for over 1,300 years, and the Dalai Lama remains a unifying spiritual and political figure. Moravian missionaries established small stations in Ladakh and the Tibetan borderlands in the 1800s but made very few converts. Today, there are estimated to be only a few hundred Tibetan Christians among a population of over 6 million.',
    population: '~6 million unreached',
    callToAction: 'On the roof of the world, where the sky meets the earth, the Creator of the mountains is calling Tibetan hearts to discover His love.',
    lat: 32,
    lng: 90,
  },
  {
    id: 'loc-40',
    name: 'The Maldivian Atolls',
    region: 'South Asia',
    flavorText: 'Paradise islands where turquoise waters hide a nation sealed against outside faith, beautiful and isolated in equal measure.',
    difficulty: 'Forgotten',
    image: 'loc-40.jpg',
    image2: 'loc-40-b.jpg',
    beliefSystem: 'Islam (Sunni)',
    whyHardToReach: 'The Maldives is constitutionally an Islamic nation where citizenship requires being Muslim. Importing non-Islamic religious materials is illegal, and conversion is punished by loss of citizenship. The island geography creates physical isolation, and the small population means any convert is immediately visible.',
    history: 'The Maldives was Buddhist before converting to Islam in 1153 AD. Since then, Islam has been the sole religion of the nation. No Christian church, fellowship, or missionary presence exists in the country. A tiny number of secret believers access Christian content through the internet, but they live in complete isolation from any believing community.',
    population: '~500,000 unreached',
    callToAction: 'Across 1,200 islands in the Indian Ocean, not a single church exists — the Maldives may be the least evangelized nation on Earth.',
    lat: 4,
    lng: 73,
  },
  {
    id: 'loc-41',
    name: 'The Comoros Channel',
    region: 'East Africa',
    flavorText: 'Volcanic islands in a warm channel where African, Arab, and Malagasy cultures blend under the crescent moon.',
    difficulty: 'Unreached',
    image: 'loc-41.jpg',
    image2: 'loc-41-b.jpg',
    beliefSystem: 'Islam (Sunni / Shafi\'i)',
    whyHardToReach: 'The Comoros is constitutionally Islamic, and proselytism of Muslims is illegal. The small island population means social control is intense, and any deviation from Islamic practice is immediately noticed. Poverty and political instability create additional barriers to sustained engagement.',
    history: 'Arab traders brought Islam to the Comoros Islands by the 8th century, and it became the dominant faith. French colonization brought a small Christian presence, but it remained among foreign residents. Today, the Comorian church numbers only a few dozen believers, mostly meeting in secret. The Adventist Church has no established presence in the country.',
    population: '~900,000 unreached',
    callToAction: 'On these volcanic islands between Africa and Madagascar, the fire of the gospel has yet to find its footing — but God is at work.',
    lat: -12,
    lng: 44,
  },
  {
    id: 'loc-42',
    name: 'The Zanzibar Straits',
    region: 'East Africa',
    flavorText: 'Spice-scented streets of ancient stone towns, where the call to prayer echoes over coral reefs and dhow harbors.',
    difficulty: 'Deep Darkness',
    image: 'loc-42.jpg',
    image2: 'loc-42-b.jpg',
    beliefSystem: 'Islam (Sunni / Ibadi / Sufi)',
    whyHardToReach: 'While Zanzibar is part of Tanzania, its Muslim-majority population maintains a distinct identity and social pressure against conversion is intense. The island\'s small size means believers have nowhere to hide, and family rejection is swift. Historical resentment of mainland Christian influence adds political tension to religious dynamics.',
    history: 'Zanzibar was a major hub of the East African slave trade and later became a center of Arab-Omani commerce. Islam has been established here for over a thousand years. David Livingstone\'s anti-slavery campaign was based partly on Zanzibar, and the Anglican Cathedral stands on the former slave market. Despite this history, the Muslim Zanzibari population remains largely unreached.',
    population: '~1.5 million unreached',
    callToAction: 'Where slave ships once sailed and chains were broken, the ultimate freedom — freedom in Christ — still waits to be proclaimed.',
    lat: -6,
    lng: 39,
  },
  {
    id: 'loc-43',
    name: 'The Karakum Desert',
    region: 'Central Asia',
    flavorText: 'A land of burning gas craters and endless sand, where one of the world\'s most isolated governments guards its people from the outside.',
    difficulty: 'Forgotten',
    image: 'loc-43.jpg',
    image2: 'loc-43-b.jpg',
    beliefSystem: 'Islam (Sunni) / Folk traditions / State control',
    whyHardToReach: 'Turkmenistan is one of the world\'s most closed societies, with severe restrictions on all religious activity outside state-approved Islam and Russian Orthodoxy. Foreign missionaries are denied entry, and local believers face imprisonment. All religious literature must be approved by the government, and importation of Bibles is illegal.',
    history: 'The Turkmen people were Islamized through Sufi missionaries centuries ago, blending Islamic practice with nomadic traditions. Soviet atheism suppressed all religion, and post-independence authoritarianism has maintained tight control. A small number of Turkmen Christians exist but worship under constant threat of arrest and harassment by security services.',
    population: '~6 million unreached',
    callToAction: 'Behind one of the world\'s most impenetrable borders, the Turkmen people live in spiritual isolation — but no wall can block the prayers of the faithful.',
    lat: 40,
    lng: 57,
  },
  {
    id: 'loc-44',
    name: 'The Fann Mountains',
    region: 'Central Asia',
    flavorText: 'Turquoise alpine lakes nestled among jagged peaks, where remote villages preserve traditions unchanged for centuries.',
    difficulty: 'Unreached',
    image: 'loc-44.jpg',
    image2: 'loc-44-b.jpg',
    beliefSystem: 'Islam (Sunni / Hanafi) / Ismaili Shia (in east)',
    whyHardToReach: 'Tajikistan\'s mountainous terrain isolates communities for months during winter. A devastating civil war in the 1990s left deep scars and distrust of outsiders. Government registration requirements for religious groups are burdensome, and unregistered religious activity faces penalties.',
    history: 'Tajikistan sits at the crossroads of Persian, Turkic, and Chinese civilizations. Zoroastrianism and Buddhism preceded Islam, which arrived through Arab conquest and Sufi missionaries. The Soviet era eliminated most religious practice, and the post-independence civil war further disrupted society. Small Christian communities exist in urban areas, but rural mountain villages remain entirely unreached.',
    population: '~9 million unreached',
    callToAction: 'In mountain villages accessible only by narrow paths, the message of hope must travel where roads cannot — carried by faith and prayer.',
    lat: 38,
    lng: 69,
  },
  {
    id: 'loc-45',
    name: 'The Hermit Kingdom',
    region: 'East Asia',
    flavorText: 'A nation shrouded in silence, where an entire generation has grown up knowing only one name to worship.',
    difficulty: 'Forgotten',
    image: 'loc-45.jpg',
    image2: 'loc-45-b.jpg',
    beliefSystem: 'Juche (state ideology) / State atheism',
    whyHardToReach: 'North Korea is consistently ranked as the most dangerous country in the world for Christians. Possession of a Bible can result in execution or lifelong imprisonment in labor camps. The state ideology of Juche functions as an enforced religion demanding total devotion to the ruling family. No legal Christian activity of any kind exists.',
    history: 'Pyongyang was once known as the "Jerusalem of the East," with a vibrant Christian community that produced many of Korea\'s early independence leaders. After the Korean War, the communist regime systematically eliminated all visible Christianity. An estimated 50,000-70,000 Christians are believed to be held in political prison camps. Underground believers risk everything to maintain their faith.',
    population: '~26 million unreached',
    callToAction: 'In the land once called the Jerusalem of the East, the light was driven underground — but it was never extinguished.',
    lat: 40,
    lng: 127,
  },
  {
    id: 'loc-46',
    name: 'The Saharan Frontier',
    region: 'West Africa',
    flavorText: 'An endless sea of sand where ancient trade routes connect scattered oasis towns under a relentless sun.',
    difficulty: 'Forgotten',
    image: 'loc-46.jpg',
    image2: 'loc-46-b.jpg',
    beliefSystem: 'Islam (Sunni / Maliki)',
    whyHardToReach: 'Mauritania practices a strict form of Islam where apostasy is punishable by death under the law. The country is one of the last places on Earth where slavery persists despite official abolition. Extreme desert conditions and sparse population make any sustained presence difficult.',
    history: 'Mauritania has been Islamic since the 11th century when Almoravid Berber warriors spread their faith across the western Sahara. The country has almost no history of Christian presence among its Arab-Berber population. A tiny number of believers exist in complete secrecy, with no established church or fellowship of any kind.',
    population: '~4.5 million unreached',
    callToAction: 'In Mauritania, where the Sahara meets the Atlantic, a nation waits in spiritual darkness for the dawn of the everlasting gospel.',
    lat: 18,
    lng: -16,
  },
  {
    id: 'loc-47',
    name: 'The Western Desert',
    region: 'North Africa',
    flavorText: 'A disputed land of sand and stone, where a displaced people await recognition beneath makeshift shelters and fading flags.',
    difficulty: 'Unreached',
    image: 'loc-47.jpg',
    image2: 'loc-47-b.jpg',
    beliefSystem: 'Islam (Sunni / Maliki)',
    whyHardToReach: 'The Sahrawi people are divided between Moroccan-controlled Western Sahara and Algerian refugee camps, creating a fractured and displaced population. The unresolved political status of the territory makes long-term ministry planning nearly impossible. Islamic identity is deeply tied to Sahrawi national identity and resistance.',
    history: 'The Sahrawi people have inhabited the Western Sahara for centuries, living as nomadic herders and traders. After Spanish withdrawal in 1975, Morocco claimed the territory, sparking a conflict that displaced over 100,000 Sahrawis to refugee camps in Algeria. Christianity has virtually no history among the Sahrawi, and there are no known established believers or churches.',
    population: '~600,000 unreached',
    callToAction: 'Among a people still waiting for a homeland, the promise of an eternal home in Christ speaks directly to the Sahrawi heart.',
    lat: 24,
    lng: -13,
  },
  {
    id: 'loc-48',
    name: 'The Neon Metropolis',
    region: 'East Asia',
    flavorText: 'A city of thirty-seven million souls bathed in electric light, yet spiritually the darkest megacity on Earth.',
    difficulty: 'Deep Darkness',
    image: 'loc-48.jpg',
    image2: 'loc-48-b.jpg',
    beliefSystem: 'Shinto / Buddhism / Secularism / New religions',
    whyHardToReach: 'Japan has less than 1% Christian population despite over 150 years of sustained missionary effort. Intense social conformity makes individual faith decisions culturally costly. Overwork culture leaves little time or energy for spiritual exploration, and deep-seated cultural Christianity-resistance views the faith as fundamentally Western.',
    history: 'Francis Xavier brought Christianity to Japan in 1549, and it grew until brutal persecution drove it underground for over 200 years. When missionaries returned in the 1850s, they discovered hidden Christians who had preserved their faith in secret. Yet modern Japan remains one of the most resistant nations to the gospel, and Tokyo — the world\'s largest metropolitan area — has fewer Christians per capita than almost any other major city.',
    population: '~37 million in metro (99% unreached)',
    callToAction: 'In the world\'s largest city, where millions pass each other without connection, the God who knows every name is seeking every heart.',
    lat: 35,
    lng: 139,
  },
  {
    id: 'loc-49',
    name: 'The Bosphorus Crossing',
    region: 'Middle East / Europe',
    flavorText: 'A city straddling two continents, where minarets and ancient churches share the same skyline across the golden strait.',
    difficulty: 'Darkness',
    image: 'loc-49.jpg',
    image2: 'loc-49-b.jpg',
    beliefSystem: 'Islam (Sunni / Hanafi) / Secularism',
    whyHardToReach: 'Turkey\'s religious identity is complex, blending secular nationalism with deep Islamic roots. Conversion from Islam carries severe social consequences, and Protestant Christians face bureaucratic obstruction and occasional violence. Nationalist sentiment views Christianity as a foreign threat to Turkish identity.',
    history: 'Istanbul was once Constantinople, capital of Eastern Christianity for over a thousand years and seat of the Ecumenical Patriarch. The seven churches of Revelation were all in modern Turkey. Today, Turkey\'s Christian population is less than 0.2%, and the historic churches of Asia Minor are empty ruins. A small but growing Turkish Protestant movement faces significant opposition.',
    population: '~82 million unreached',
    callToAction: 'In the land of the seven churches of Revelation, where Paul and the apostles walked, the final message must echo once more.',
    lat: 41,
    lng: 29,
  },
  {
    id: 'loc-50',
    name: 'The City of a Thousand Minarets',
    region: 'North Africa / Middle East',
    flavorText: 'A teeming ancient capital where the call to prayer rolls across rooftops in waves, and the weight of history presses on every street.',
    difficulty: 'Deep Darkness',
    image: 'loc-50.jpg',
    image2: 'loc-50-b.jpg',
    beliefSystem: 'Islam (Sunni) / Coptic Christianity (minority)',
    whyHardToReach: 'Cairo\'s 20+ million inhabitants live in one of the most densely populated cities on Earth, creating logistical challenges for any outreach. While Egypt\'s Coptic Christians are a significant minority, evangelism among Muslims is socially taboo and legally gray. Sectarian tensions and periodic violence make interfaith engagement sensitive.',
    history: 'Egypt was one of the earliest strongholds of Christianity, home to the Desert Fathers and the Alexandrian theological school. The Coptic Church has survived 14 centuries of Islamic rule with remarkable resilience. However, the vast Muslim majority — including millions in Cairo\'s informal settlements — has had minimal exposure to biblical Christianity beyond cultural stereotypes.',
    population: '~90 million unreached',
    callToAction: 'In the land of the pharaohs and the exodus, where Moses once stood, the God of deliverance is still calling His people out.',
    lat: 30,
    lng: 31,
  },
  {
    id: 'loc-51',
    name: 'The Delhi Labyrinth',
    region: 'South Asia',
    flavorText: 'Narrow lanes teeming with life, where ancient Mughal grandeur crumbles beside sprawling slums and the air carries a thousand prayers.',
    difficulty: 'Darkness',
    image: 'loc-51.jpg',
    image2: 'loc-51-b.jpg',
    beliefSystem: 'Hinduism / Islam / Sikhism',
    whyHardToReach: 'Delhi\'s vast urban slums house millions of people in grinding poverty with minimal access to healthcare, education, or religious outreach. Rising Hindu nationalism has intensified pressure on Christians through anti-conversion laws and mob violence. The city\'s overwhelming scale and diversity make any single approach insufficient.',
    history: 'Delhi has been the seat of empires for a thousand years — Hindu, Muslim, Sikh, and British. Christian missions established hospitals and schools during the colonial era, many of which still operate. Yet the city\'s explosive growth has far outpaced any Christian presence, and millions in Delhi\'s informal settlements have never encountered the gospel in a meaningful way.',
    population: '~30 million in metro (vast majority unreached)',
    callToAction: 'In the labyrinth of Old Delhi and the sprawl of New Delhi, every narrow lane is an invitation to carry the light where it has not yet shone.',
    lat: 28,
    lng: 77,
  },
  {
    id: 'loc-52',
    name: 'The Highland Valleys of Papua',
    region: 'Oceania',
    flavorText: 'Mist-shrouded valleys hidden by impassable mountains, where tribes live in worlds entirely their own.',
    difficulty: 'Unreached',
    image: 'loc-52.jpg',
    image2: 'loc-52-b.jpg',
    beliefSystem: 'Animism / Ancestor worship / Christianity (coastal)',
    whyHardToReach: 'Papua New Guinea has over 800 languages — the most linguistically diverse nation on Earth — and many highland tribes have had minimal outside contact. Dense jungle and mountainous terrain make many communities accessible only by small aircraft or days of trekking. Tribal warfare and sorcery-related violence continue in remote areas.',
    history: 'Christian missionaries began reaching PNG\'s coast in the 1870s, and the interior highlands were contacted only in the mid-20th century. Remarkable gospel movements have transformed many tribes, but hundreds of small language groups in the most remote valleys remain unreached. The Adventist Church has significant membership in PNG but concentrates in accessible areas.',
    population: '~3 million unreached in highlands',
    callToAction: 'In valleys so remote they were unknown to the outside world until living memory, the Creator has always known every name.',
    lat: -6,
    lng: 144,
  },
  {
    id: 'loc-53',
    name: 'The Amazon Headwaters',
    region: 'South America',
    flavorText: 'Dense jungle canopy hiding the last uncontacted peoples on Earth, living as they have for millennia beside rivers that know no bridges.',
    difficulty: 'Forgotten',
    image: 'loc-53.jpg',
    image2: 'loc-53-b.jpg',
    beliefSystem: 'Animism / Shamanism / Indigenous spirituality',
    whyHardToReach: 'Several dozen uncontacted tribes in the Amazon basin are protected by law from outside contact, creating ethical dilemmas for mission engagement. Contacted but unreached tribes face threats from illegal mining, logging, and land encroachment. Language barriers are extreme, with many tribal languages having no written form.',
    history: 'Catholic missionaries entered the Amazon during the colonial era, often with devastating consequences for indigenous populations through disease and forced labor. Protestant missions in the 20th century, including SIL Bible translators, made significant inroads among some tribes. The Adventist Church operates river launches providing medical and educational services to remote communities along the Amazon and its tributaries.',
    population: '~1 million unreached indigenous',
    callToAction: 'In the world\'s greatest rainforest, where creation displays God\'s power in every leaf and creature, hidden peoples await His voice.',
    lat: -5,
    lng: -65,
  },
  {
    id: 'loc-54',
    name: 'The Andaman Shores',
    region: 'South Asia',
    flavorText: 'Emerald islands guarded by coral reefs and the arrows of those who wish to remain unseen.',
    difficulty: 'Forgotten',
    image: 'loc-54.jpg',
    image2: 'loc-54-b.jpg',
    beliefSystem: 'Indigenous animism / Hinduism (settlers)',
    whyHardToReach: 'The indigenous Andamanese peoples — including the Sentinelese, Jarawa, and others — are among the most isolated people on Earth. Indian law prohibits contact with the Sentinelese and restricts access to Jarawa territory. Disease from outside contact has devastated indigenous populations historically, raising profound ethical questions about engagement.',
    history: 'The Andaman Islands are home to peoples who may have been isolated for up to 60,000 years. British colonization decimated many groups through disease and violence. The Sentinelese have violently rejected all outside contact, including a missionary who was killed attempting to reach them in 2018. The Great Andamanese and Onge peoples have been reduced to tiny remnant populations.',
    population: '~500 indigenous unreached',
    callToAction: 'On islands where the most isolated humans on Earth guard their solitude, the church must wrestle with how love reaches those who do not wish to be found.',
    lat: 11,
    lng: 92,
  },
  {
    id: 'loc-55',
    name: 'The Chechen Highlands',
    region: 'Eurasia',
    flavorText: 'War-scarred towers stand sentinel over rebuilt streets, where fierce independence and deep faith forge an unbreakable identity.',
    difficulty: 'Forgotten',
    image: 'loc-55.jpg',
    image2: 'loc-55-b.jpg',
    beliefSystem: 'Islam (Sunni / Sufi) / Chechen Sufi traditions',
    whyHardToReach: 'Two devastating wars have created a traumatized and insular society deeply suspicious of outside influence. Sufi Islam is central to Chechen national identity, and conversion is considered treason against the people. Authoritarian governance monitors all religious activity and would not tolerate Christian outreach.',
    history: 'The Chechen people adopted Islam gradually from the 16th to 19th centuries, blending it with Sufi mysticism and pre-Islamic mountain traditions. Russian colonization triggered centuries of resistance, and the wars of the 1990s-2000s destroyed much of the country. Despite a small Russian Orthodox presence in neighboring areas, there is virtually no indigenous Christian witness among ethnic Chechens.',
    population: '~1.5 million unreached',
    callToAction: 'Among the Chechen people, shaped by suffering and resilience, the peace of Christ offers healing that reconstruction alone cannot bring.',
    lat: 43,
    lng: 45,
  },
  {
    id: 'loc-56',
    name: 'The Dagestani Highlands',
    region: 'Eurasia',
    flavorText: 'A land of a hundred languages spoken in a hundred mountain villages, each valley a world unto itself.',
    difficulty: 'Unreached',
    image: 'loc-56.jpg',
    image2: 'loc-56-b.jpg',
    beliefSystem: 'Islam (Sunni / Sufi / Salafi)',
    whyHardToReach: 'Dagestan is the most ethnically and linguistically diverse region in Europe, with over 30 ethnic groups and languages in a single republic. An ongoing insurgency and security operations make many areas dangerous. Each ethnic group requires a distinct cultural approach, making scaled outreach nearly impossible.',
    history: 'Dagestan — meaning "land of mountains" — has been Muslim since the Arab conquests of the 7th-8th centuries, making it one of the oldest Islamic regions in Russia. The region has experienced waves of religious radicalization and government crackdowns. Christian presence is limited to a few small Russian-speaking congregations in urban areas, with essentially no indigenous believers among Dagestan\'s many ethnic groups.',
    population: '~3 million unreached',
    callToAction: 'In the land of mountains and a hundred languages, the God who spoke at Pentecost in every tongue has a message for every people.',
    lat: 42,
    lng: 47,
  },
  {
    id: 'loc-57',
    name: 'The Brahmaputra Floodplains',
    region: 'South Asia',
    flavorText: 'River islands that appear and vanish with the floods, home to communities as impermanent as the land beneath their feet.',
    difficulty: 'Darkness',
    image: 'loc-57.jpg',
    image2: 'loc-57-b.jpg',
    beliefSystem: 'Islam (Sunni) / Hinduism / Tribal religions',
    whyHardToReach: 'The char (river island) communities of the Brahmaputra are among the most vulnerable on Earth, displaced by annual flooding and lacking permanent infrastructure. Ethnic tensions between Bengali Muslim settlers and indigenous tribal groups create volatile social dynamics. Geographic isolation and poverty make sustained ministry almost impossible.',
    history: 'The Brahmaputra valley has been a corridor of migration and cultural exchange for millennia, with Hindu, Buddhist, and Islamic influences layering over indigenous tribal practices. British-era tea plantations brought Christianity among tribal workers, but the vast Muslim population along the floodplains remains unreached. The shifting river islands host some of the most marginalized communities in South Asia.',
    population: '~20 million unreached',
    callToAction: 'On islands that shift with every monsoon, the unchanging love of God offers solid ground to those who have known only uncertainty.',
    lat: 26,
    lng: 91,
  },
  {
    id: 'loc-58',
    name: 'The Tuareg Sahara',
    region: 'West Africa / North Africa',
    flavorText: 'Blue-robed nomads crossing a sea of sand, guided by stars and traditions older than the desert itself.',
    difficulty: 'Unreached',
    image: 'loc-58.jpg',
    image2: 'loc-58-b.jpg',
    beliefSystem: 'Islam (Sunni / Maliki) / Pre-Islamic Tuareg traditions',
    whyHardToReach: 'The Tuareg people are nomadic across five Saharan nations — Mali, Niger, Algeria, Libya, and Burkina Faso — making coordinated outreach extremely complex. Armed conflict and terrorism in the Sahel have made much of Tuareg territory unsafe. Tuareg identity combines Islam with a fierce independence that resists outside religious influence.',
    history: 'The Tuareg are a Berber people who have traversed the Sahara for over two thousand years as traders, guides, and warriors. They adopted Islam gradually but maintained many pre-Islamic customs, including a matrilineal social structure unusual in the Islamic world. A Tuareg rebellion in Mali in 2012 and the ongoing Sahel crisis have displaced many communities. There are virtually no known Tuareg Christians.',
    population: '~3 million unreached',
    callToAction: 'Across the vast Sahara, where Tuareg caravans have traveled for millennia, the greatest journey — to the heart of God — has yet to begin.',
    lat: 17,
    lng: 8,
  },
  {
    id: 'loc-59',
    name: 'The Caspian Shores',
    region: 'Central Asia',
    flavorText: 'Oil rigs and fishing boats dot an ancient inland sea, where modernization and tradition wrestle for the soul of a nation.',
    difficulty: 'Deep Darkness',
    image: 'loc-59.jpg',
    image2: 'loc-59-b.jpg',
    beliefSystem: 'Islam (Shia majority) / Secularism',
    whyHardToReach: 'While officially secular, cultural Islam permeates society and conversion carries heavy social stigma. Government control of religious organizations requires registration and limits activities of non-traditional groups. Oil wealth has created a materialistic urban culture that competes with spiritual concerns.',
    history: 'The Caspian region of Azerbaijan was Zoroastrian before Islam arrived through Arab conquest. Known as the "Land of Fire" for its natural gas seeps, the region has been shaped by Persian, Turkish, Russian, and Soviet influences. Soviet-era atheism weakened religious practice, and post-independence nationalism blended secular and Islamic identity. A small but growing community of Azerbaijani believers exists, facing social pressure but not the extreme persecution seen in neighboring countries.',
    population: '~10 million unreached',
    callToAction: 'In the land of eternal flames, where fire once symbolized the divine, the true Light of the world is beginning to shine.',
    lat: 41,
    lng: 50,
  },
  {
    id: 'loc-60',
    name: 'The Minangkabau Highlands',
    region: 'Southeast Asia',
    flavorText: 'Soaring rooflines like buffalo horns crown villages where the world\'s largest matrilineal Muslim society maintains its unique traditions.',
    difficulty: 'Darkness',
    image: 'loc-60.jpg',
    image2: 'loc-60-b.jpg',
    beliefSystem: 'Islam (Sunni / Shafi\'i) / Adat (customary law)',
    whyHardToReach: 'The Minangkabau are devout Muslims who simultaneously maintain a matrilineal cultural system, creating a unique and deeply embedded identity. Conversion is seen as abandoning both religion and culture, resulting in complete social exclusion. The blending of Islamic law and adat (customary law) creates a dual system that reinforces resistance to outside faith.',
    history: 'The Minangkabau of West Sumatra are the world\'s largest matrilineal society and are known across Indonesia for their intellectual and entrepreneurial spirit. Islam spread among them through Sufi teachers in the 16th century and was solidified through the Padri War of the early 1800s. Despite being surrounded by significant Christian populations in neighboring Batak lands, the Minangkabau remain one of the largest unreached Muslim people groups in Southeast Asia.',
    population: '~8 million unreached',
    callToAction: 'Among a people known for their wisdom and wandering spirit, the God who calls all peoples to Himself has a place prepared for the Minangkabau.',
    lat: -0.5,
    lng: 100,
  },
];

/** Shuffle and pick mission locations for a game (Fisher-Yates shuffle) */
export function pickMissionLocations(count: number): MissionLocation[] {
  const shuffled = [...MISSION_LOCATIONS];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled.slice(0, count);
}
